version: 2
updates:
- package-ecosystem: bundler
  directory: '/'
  schedule:
    interval: daily
    time: '03:00'
    timezone: 'Asia/Tokyo'
  open-pull-requests-limit: 0
  target-branch: master
  versioning-strategy: lockfile-only
- package-ecosystem: bundler
  directory: '/'
  schedule:
    interval: daily
    time: '03:00'
    timezone: 'Asia/Tokyo'
  open-pull-requests-limit: 0
  target-branch: develop
  versioning-strategy: lockfile-only
