version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3
    working_directory: ~/repos
    steps:
      - checkout
      - run:
          name: install bundler
          command: gem install bundler
      - run:
          name: install dependencies
          command: bundle install
      - run:
          name: run RuboCop
          command: bundle exec rubocop
      - run:
          name: update repository
          command: bundle exec rake repos:update
      - run:
          name: check repository
          command: bundle exec rake repos:check
