version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3
      - image: circleci/postgres:9.6.12
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: mastodon
      - image: redis:4.0.14
    working_directory: ~/repos
    steps:
      - checkout
      - run:
          name: install bundler
          command: gem install bundler
      - run:
          name: install dependencies
          command: bundle install
      - run:
          name: run RuboCop
          command: bundle exec rubocop
      - run:
          name: run rails-erb-lint
          command: bundle exec rake erb:check
      - run:
          name: update repository
          command: bundle exec rake repos:update
      - run:
          name: check repository
          command: bundle exec rake repos:check
      - run:
          name: run test
          command: bundle exec rake test
