inflections:
  amazon_uri: AmazonURI
  amazon_url_handler: AmazonURLHandler
  api_controller: APIController
  canonical_url_handler: CanonicalURLHandler
  css_renderer: CSSRenderer
  custom_api: CustomAPI
  custom_api_render_storage: CustomAPIRenderStorage
  ffmpeg_command_builder: FFmpegCommandBuilder
  http: HTTP
  itunes_album_uri: ItunesAlbumURI
  itunes_song_uri: ItunesSongURI
  itunes_track_uri: ItunesTrackURI
  itunes_uri: ItunesURI
  itunes_url_handler: ItunesURLHandler
  itunes_url_nowplaying_handler: ItunesURLNowplayingHandler
  mime_type: MIMEType
  note_uri: NoteURI
  oauth_client_storage: OAuthClientStorage
  peer_tube_uri: PeerTubeURI
  peer_tube_url_nowplaying_handler: PeerTubeURLNowplayingHandler
  poipiku_uri: PoipikuURI
  rss20_feed_renderer: RSS20FeedRenderer
  shortened_url_handler: ShortenedURLHandler
  sns_methods: SNSMethods
  sns_service_methods: SNSServiceMethods
  spotify_uri: SpotifyURI
  spotify_url_handler: SpotifyURLHandler
  spotify_url_nowplaying_handler: SpotifyURLNowplayingHandler
  toot_uri: TootURI
  ui_controller: UIController
  uri: URI
  url_handler: URLHandler
  url_normalize_handler: URLNormalizeHandler
  you_tube_url_nowplaying_handler: YouTubeURLNowplayingHandler
  you_tube_video_uri: YouTubeVideoURI
