- key: /spoiler/pattern
  aliases:
    - /annict/spoiler/pattern
    - /handler/spoiler/pattern
- key: /alert/slack/hooks
  aliases:
    - /slack/hooks
- key: /spotify/client/secret
  aliases:
    - /spotify/client_secret
- key: /crypt/salt
  aliases:
    - /webhook/salt
- key: /mastodon/status/field
  aliases:
    - /mastodon/toot/field
- key: /mastodon/status/key
  aliases:
    - /mastodon/toot/key
- key: /mastodon/status/label
  aliases:
    - /mastodon/toot/label
- key: /mastodon/status/max_length
  aliases:
    - /mastodon/toot/max_length
- key: /mastodon/status/visibility_names/unlisted
  aliases:
    - /mastodon/toot/visility_names/unlisted
- key: /mastodon/status/visibility_names/private
  aliases:
    - /mastodon/toot/visility_names/private
- key: /mastodon/status/visibility_names/direct
  aliases:
    - /mastodon/toot/visility_names/direct
- key: /mastodon/status/patterns
  aliases:
    - /mastodon/toot/patterns
- key: /mastodon/attachment/key
  aliases:
    - /mastodon/media/key
- key: /misskey/status/field
  aliases:
    - /misskey/note/field
- key: /misskey/status/key
  aliases:
    - /misskey/note/key
- key: /misskey/status/label
  aliases:
    - /misskey/note/label
- key: /misskey/status/max_length
  aliases:
    - /misskey/note/max_length
- key: /misskey/status/visibility_names/unlisted
  aliases:
    - /misskey/note/visility_names/unlisted
- key: /misskey/status/visibility_names/private
  aliases:
    - /misskey/note/visility_names/private
- key: /misskey/status/visibility_names/direct
  aliases:
    - /misskey/note/visility_names/direct
- key: /misskey/status/patterns
  aliases:
    - /misskey/note/patterns
- key: /misskey/attachment/key
  aliases:
    - /misskey/file/key
- key: /handler/shortened_url/domains
  aliases:
    - /shortened_url/domains
